package org.zalando.nakadi.client.java.model;

public class Problem {
    private final String problemType;
    private final String title;
    private final Integer status;
    private final String detail;
    private final String instance;
    
    /**
     * @ param problemType An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable API documentation for the problem type (e.g., using HTML). This Problem object is the same as provided by https://github.com/zalando/problem
     * @ param title A short, summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized)
     * @ param status The HTTP status code generated by the origin server for this occurrence of the problem.
     * @ param detail A human readable explanation specific to this occurrence of the problem.
     * @ param instance An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     */
    public Problem(String problemType, String title, Integer status, String detail, String instance) {
        this.problemType = problemType;
        this.title = title;
        this.status = status;
        this.detail = detail;
        this.instance = instance;
    }
    public String getProblemType() {
        return problemType;
    }
    public String getTitle() {
        return title;
    }
    public Integer getStatus() {
        return status;
    }
    public String getDetail() {
        return detail;
    }
    public String getInstance() {
        return instance;
    }
    
    
    
}
