package org.zalando.nakadi.client.java.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a Poblem Type.
 *
 */
public class Problem {
    private final String type;
    private final String title;
    private final Integer status;
    private final String detail;
    private final String instance;

    /**
     * @param type
     *            Identifies the problem type.
     * @param title
     *            A short, summary of the problem type.
     * @param status
     *            The HTTP status code generated by the origin server for this occurrence of the problem.
     * @param detail
     *            A human readable explanation specific to this occurrence of the problem.
     * @param instance
     *            An absolute URI that identifies the specific occurrence of the problem.
     */
    @JsonCreator
    public Problem(@JsonProperty("type") String type, @JsonProperty("title") String title, @JsonProperty("status") Integer status, @JsonProperty("detail") String detail,
            @JsonProperty("instance") String instance) {
        this.type = type;
        this.title = title;
        this.status = status;
        this.detail = detail;
        this.instance = instance;
    }

    public String getType() {
        return type;
    }

    public String getTitle() {
        return title;
    }

    public Integer getStatus() {
        return status;
    }

    public String getDetail() {
        return detail;
    }

    public String getInstance() {
        return instance;
    }

    @Override
    public String toString() {
        return "Problem [type=" + type + ", title=" + title + ", status=" + status + ", detail=" + detail + ", instance=" + instance + "]";
    }

}
